apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Name}}
{{if not (eq (Mod .Index 20) 0 19) }} # .Index % 20 in {0,19} - only 10% deployments will have non-immutable ConfigMap.
immutable: true
{{end}}
data:
  data.yaml: |-
    a: 1
    b: 2
    c: 3
